<?php

namespace App\Http\Middleware;

use Closure;
use Laravel\Horizon\Horizon;
use App\Facades\Horizon as HorizonService;

/**
 * Class AuthenticateHorizon
 * @package App\Http\Middleware
 */
class AuthenticateHorizon
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        /** @var boolean| $authenticated */
        $authenticated = HorizonService::handleAuth($request);

        // check if HorizonService::handleAuth has return a boolean
        if (is_bool($authenticated)) {
            Horizon::auth(function ($request) use ($authenticated) {
                return $authenticated;
            });
        } else { // return redirection generated by HorizonService::handleAuth
            return $authenticated;
        }

        return $next($request);
    }
}
