<?php
/**
 * Created by PhpStorm.
 * User: loiclopez
 * Date: 19/09/2018
 * Time: 18:44
 */

/**
 * @OA\Post(
 *      path="/auth/login",
 *      operationId="loginUser",
 *      tags={"Auth"},
 *      @OA\RequestBody(
 *         required=true,
 *         @OA\MediaType(
 *             mediaType="application/json",
 *             @OA\Schema(ref="#/components/schemas/Login")
 *         )
 *     ),
 *      summary="Login a user",
 *      description="Login user and returns tokens generated by Passport route : /oauth/tokens",
 *      @OA\Response(
 *          response=200,
 *          description="successful operation",
 *          @OA\JsonContent(ref="#/components/schemas/TokenResponse")
 *       ),
 *       @OA\Response(
 *          response=422,
 *          description="The given parameters were faulty",
 *          @OA\JsonContent(ref="#/components/schemas/ErrorResponse")
 *       )
 *     )
 **/
